---
- hosts: all
  tasks:

  - name: omero | print ansible version
    debug:
        msg: "Ansible version: {{ ansible_version }}"
    always_run: True

  - name: omero | venv is broken on ansible 2.2
    fail: msg="This playbook does not work on Ansible 2.2 or greater."
    when: ansible_version.major ==  2 and ansible_version.minor >= 2
    always_run: True

- hosts: all
  roles:
    - role: ansible-role-omero-server
      postgresql_users_databases:
      - user: omero
        password: omero
        databases: [omero]
      omero_systemd_setup: True
      omero_server_systemd_require_network: False
      omero_system_managedrepo_group: importer


# Additional tasks for setting up tests
- hosts: all
  tasks:

  - name: create import user
    user:
      name: data-importer
      group: importer

  - name: create data directory
    file:
      path: /data/import
      state: directory

  - name: create fake image
    copy:
      content: ''
      dest: /data/import/test.fake

# testinfra Sudo doesn't use the `-i` flag, so the working directory needs
# to be accessible
- hosts: vagrant-hosts
  tasks:
  - name: make vagrant home accessible
    file:
      owner: vagrant
      group: vagrant
      mode: "0711"
      path: /home/vagrant
      state: directory
